layout_spectrum: 0
typography_spectrum: 0.4924115
color:
  saturation: 0.8953572
  lightness: 0.2501697
  brandStrength: 0.9673827
  rhythmicContrast: 0.2224543
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: MissAce
